### ISSUE TITLE
ERROR: Superclass 'Object' of class 'SuperColliderJS' is not defined in any file

### ISSUE THREAD

**Issue by cannc4** [lorenzorivosecchi/electron-with-supercollider-example#1]
Hi, I am trying to give this a spin with the latest SC version and hit the error above, any thoughts?

**Comment by fibonacid** [comment]
Hello, I don't know how you get to this error, can you list the steps to reproduce it ?

**Comment by cannc4** [comment]
Hi @lorenzorivosecchi thanks for the prompt answer.

Here is my config to boot up the SCLang
```
async function bootSclang() {
  const options = {
    debug: true,
    echo: true,
    sclang: vendor('SuperCollider/MacOS/sclang'),
    sclang_conf: null
  }
  try {
    const lang = await sc.lang.boot(options)
    await lang.interpret('s.boot')
  } catch(err) {
    console.error(err)
  }
}
```

I've also followed your guide on what to put in the `vendor/mac/supercollider`. On a related note, I've just downloaded the latest SC and tested your repo with it. No luck.

**Comment by cannc4** [comment]
I am thinking it might be related with the latest Catalina update or the SC version somehow. If you think that might be the case I'll look into downgrading.
Also opened up an issue in the SCJS repo(https://github.com/crucialfelix/supercolliderjs/issues/82) as that's where the problem occurs. I can open up the SC on my local just fine.

**Comment by cannc4** [comment]
An update:
After getting some help from SuperColliderJS's author I managed to get the SC running on my local using the binary. SCClassLibrary was missing from the `MacOS` so might be something to add to your repo's `README.md`

Now I am trying to find a solution for the signing problem as you mentioned in your notes. 
Do you have any thoughts for me on that matter? In theory we want to embed the binary and sign it within the notarization.

**Comment by fibonacid** [comment]
I ended up with that recipe by trail and error.
For troubleshooting i would suggest to launch the sclang binary directly from the terminal and see what happens.

```bash
QT_DEBUG_PLUGINS=1 ./vendor/SuperCollider/MacOS/sclang
```

The signing issue is there because MacOS refuses to sign the SuperCollider library.
If i remember correctly the error was something like "Cannot sign a framework".

**Comment by cannc4** [comment]
Yeah that's the issue. Can't really sign the SC binary for some reason.
Even if I add the signed version instead, it still gives me some funny errors. 
```
  {
      "severity": "error",
      "code": null,
      "path": "SND.zip/SND.app/Contents/Resources/app.asar.unpacked/vendor/mac/SuperCollider/Resources/plugins/UIUGens.scx",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "SND.zip/SND.app/Contents/Resources/app.asar.unpacked/vendor/mac/SuperCollider/Resources/plugins/UIUGens.scx",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    }
```
